### ISSUE TITLE
fabric8-maven-plugin not getting correct api server from .kube/config

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8#4687]
Seems to require KUBERNETES_MASTER environment variable... if that variable is not there, we get this (below)... was hoping it would automatically grab from the .kube/config file

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:2.3-SNAPSHOT:apply (default-cli) on project kubernetes-maven-sample: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:2.3-SNAPSHOT:apply failed: Could not create HTTP client: no protocol: /api/v1/ -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:2.3-SNAPSHOT:apply (default-cli) on project kubernetes-maven-sample: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:2.3-SNAPSHOT:apply failed: Could not create HTTP client
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:2.3-SNAPSHOT:apply failed: Could not create HTTP client
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Could not create HTTP client
        at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:185)
        at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:113)
        at io.fabric8.maven.AbstractNamespacedMojo.getKubernetes(AbstractNamespacedMojo.java:53)
        at io.fabric8.maven.ApplyMojo.execute(ApplyMojo.java:159)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        ... 20 more
Caused by: java.net.MalformedURLException: no protocol: /api/v1/
        at java.net.URL.<init>(URL.java:585)
        at java.net.URL.<init>(URL.java:482)
        at java.net.URL.<init>(URL.java:431)
        at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:125)
        ... 24 more

**Comment by jimmidyson** [comment]
This seems to work fine for me. Is `KUBERNETES_MASTER` env var unset or empty?

**Comment by davsclaus** [comment]
I only has this ENV set

davsclaus:/workspace/quickstarts/quickstart/cdi/camel (master)/$ export | grep -i KUBE
declare -x KUBERNETES_DOMAIN="vagrant.f8"

And I deploy fine to OS on vagrant and my kube config is
```
davsclaus:/workspace/quickstarts/quickstart/cdi/camel (master)/$ cat ~/.kube/config
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://172.28.128.4:8443
  name: 172-28-128-4:8443
contexts:
- context:
    cluster: 172-28-128-4:8443
    namespace: default
    user: admin/172-28-128-4:8443
  name: default/172-28-128-4:8443/admin
current-context: default/172-28-128-4:8443/admin
kind: Config
preferences: {}
users:
- name: admin/172-28-128-4:8443
  user:
    token: CcxAKBBaMo43VpIMIs8oBZVfioe84jje53iMgM2d9uk
```

As a lot has changed in 1 month. Then closing as assume working on latest code. @christian-posta you can try again if you can see to reproduce with latest release.
