### ISSUE TITLE
lets add a yaml file for each Jenkins workflow groovy script in the standard library to add metadata about the environments and stages available in the flow

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#5255]
e.g. something like

```
-
 description: Release, Integration test, Stage, Approve then promote to Production
 environments:
   Testing: ${project-name}-testing
   Staging: ${project-name}-staging
   Production: ${project-name}-prod
 stages:
  - Release
  - Stage
  - Approve
  - Production
 labels:
   production: approve
   stage: automatic
 diagram: SomePipeline.svg
```

then the UI can provide a nicer way to view/filter pipelines
