### ISSUE TITLE
the cdi-camel-mq quickstart creates a service with tcp port 1

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#5416]
wonder if its the headless or a new bug in the fabric8:json goal or something.

**Comment by jimmidyson** [comment]
Headless.  See clusterIP=None.

**Comment by davsclaus** [comment]
Ah it could be the json generates it as

Type
ClusterIP

which is what i see from the web console

**Comment by jimmidyson** [comment]
But this shouldn't cause any problems?

**Comment by davsclaus** [comment]
So the yml has something a like
```
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      prometheus.io/scheme: "http"
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      project: "cdi-camel"
      component: "cdi-camel"
      container: "java"
      provider: "fabric8"
      group: "quickstarts"
      version: "2.2.78-SNAPSHOT"
    name: "cdi-camel"
  spec:
    clusterIP: "None"
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 1
    selector:
      project: "cdi-camel"
      component: "cdi-camel"
      container: "java"
      provider: "fabric8"
      group: "quickstarts"
```
So it has none in clusterIP. But the tcp port 1 mapping is that correct, @jimmidyson ?
