### ISSUE TITLE
add a Git link to the fabric8.yml

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5598]
A typical fabric8.yml looks like..
```
---
pipeline: "workflows/maven/CanaryReleaseAndStage/Jenkinsfile"
buildName: "jr-test30"
codeReview: false
links:
  Job: "http://jenkins.vagrant.f8/job/jr-test30"
  Staging: "http://fabric8.vagrant.f8/kubernetes/pods?namespace=jr-test30-staging"
  Testing: "http://fabric8.vagrant.f8/kubernetes/pods?namespace=jr-test30-testing"
environments:
  Testing: "jr-test30-testing"
  Staging: "jr-test30-staging"
useLocalFlow: true
```

@jstrachan would it be straight forward to add a an extra link that points to the Git repo whether its been created or imported from gogs / github / gitlab etc?

At the moment we're working it out in the maven plugin today but soon the kubernetes-workflow plugin, when we add build annotations https://github.com/fabric8io/fabric8/blob/master/fabric8-maven-plugin/src/main/java/io/fabric8/maven/AbstractFabric8Mojo.java#L501-L534

If its in the fabric8.yml it would be easier to get hold of.
