### ISSUE TITLE
alternative approach to generating JSON / YAML kubernetes resources

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#5861]
the current maven properties approach is a little bit cryptic & hard to tool. Its also totally maven centric - we need a more polyglot / poly-build-tool approach. I wonder if we can come up with a simpler to understand and easier to tool approach that can work for many languages? 

The original main motivation was all the labels + selectors were error prone and we wanted to do a better job of adding smart defaults - and adding extra labels/annotations etc.

How about this as a strawman...

* folks can create yaml/json files (yaml are probably easier for humans to write?) in `src/main/kubernetes` (different build systems / languages can use a different folder if they prefer).
* folks can define very minimal contents in there. e.g. for an RC it could be this file `src/main/kubernetes/rc.yml`...

```
---
apiVersion: "v1"
kind: "ReplicationController"
metadata:
  name: "foo"
  labels:
    project: "whatnot"
    version: "${project.version}"
  annotations:
spec:
  template:
    spec:
      containers:
      - image:  "foo/bar:${project.version}"
```

mostly its gonna require the image name really and the kind; everything else could be ommitted. e.g. we could default
* the name
* the labels
* the labels can be replicated on an RC for the selector and pod templatess labels

e.g. it could be this simple:
```
---
apiVersion: "v1"
kind: "ReplicationController"
metadata:
  labels:
  annotations:
spec:
  template:
    spec:
      containers:
      - image:  "foo/bar:${project.version}"
```

Then there's a natural place for folks to add labels / annotations as they require - or add any k8s stuff needed. 

The same can be true of other resources like services. e.g. `src/main/kubernetes/service-http.yml` could be:

```
---
apiVersion: "v1"
kind: "Service"
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: "LoadBalancer"
```

again we can default the name, labels, selector of the resource along with the port name & protocol by default.

We can then add all the other generated annotations we add like icons, git commit, git URL, CI job and all that jazz too.

The basic idea is to have small simple YML files that users edit; with minimal required OOTB data to type. Most stuff can be generated (labels and whatnot) from project metadata. At any time folks can be specific in the files (e.g. add the exact labels required - possibly with variable filtering to refer to maven versions and stuff)- which then overrides the OOTB generated values. Then we can replicate labels in RCs / Services to selectors + pod template labels if they are not supplied.

i.e. a convention over configuration approach; but the data folks type is actually put into the real YML file - so one day we could have a nice IDE / UI for editing it with validation / completion etc.

We'd need to also support generating OpenShift Templates. I do wonder if we'll just move to vanilla k8s resources and ConfigMap really though. But we should maybe allow a `src/main/kubernetes/template.yml` to be generated containing all the parameter definitions and default values (in which case all the other resources would be put inside the Template I guess).

Thoughts?

**Comment by jimmidyson** [comment]
A lot of the reasons that we originally moved to generating stuff, e.g. ensuring same labels in RC & pod spec, have been improved in kubernetes via better defaulting on requested objects, e.g. if RC selector labels are omitted in request then default it to pod asked spec. Although I see the need for adding extra stuff, enriching the manifest with stuff we require for CD, etc, I think it's worth looking at whether the need for so much generation is still required with the defaulting we have & also looking at better support for the most widely used deployment format (I assume that is helm, or deployment manager is it now with helm merged in). If manifests are already pretty minimal I would hesitate to introduce an intermediate yaml schema for users to learn in addition to the standard kubernetes yaml schema.

**Comment by jstrachan** [comment]
@jimmidyson totally agreed. BTW to be clear I wasn't suggesting any intermediate yaml formats; I meant to reuse the exact schema of resources from upstream kubernetes. All I really meant was that we can be even more sparse in those than you can be in kubernetes.

e.g.  we can default all these values OOTB:
```
apiVersion: v1
metadata:
  creationTimestamp: null
  name: ${project.artifactId}
  labels:
    group: ${project.groupId}
    project: ${project.artifactId}
    version: ${project.version}
```
so folks don't have to provide name or labels at all if they don't want to - as we can typically infer those from the maven of things.

Mostly though its about enriching really (e.g. adding the CD annotations for icons, git commit and jenkins builds etc)

**Comment by rhuss** [comment]
Good idea ;) Couldn't we go the same route as d-m-p to support both, a pom-config and a template approach ?  So that we have a route from a super-simple use case (service + RC completely generated from one or two props) to full support for templated k8s resource descriptors ?

**Comment by rajdavies** [comment]
good idea - things get complicated very quickly for more than very simple cases - would be good to support both

**Comment by jstrachan** [comment]
@rhuss we could; though I'm hoping the rc.yml and service.yml are so simple and concise, doing it the YAML way seems pretty straightforward even for the simple use case.

e.g.

```
# rc.yml
---
kind: "ReplicationController"
spec:
  template:
    spec:
      containers:
      - image:  "foo/bar:${project.version}"

# service-http.yml
---
kind: "Service"
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: "LoadBalancer"
```

Also the new project wizard could auto-create these 2 YAML files like we auto-populate the maven properties so folks just create a project (e.g. from a maven archetype) and you get the rc.yml / service-http.yml created for you
