### ISSUE TITLE
logging app doesn't run from the console

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5862]
When running the logging app from the console I see the errors below however running the yaml from the command line works.
```
kind: Status
apiVersion: v1
metadata: {}
status: Failure
message: 'Service "elasticsearch" is invalid: spec.clusterIP: Invalid value: "": field is immutable'
reason: Invalid
details:
  name: elasticsearch
  kind: Service
  causes:
    - reason: FieldValueInvalid
      message: 'Invalid value: "": field is immutable'
      field: spec.clusterIP
code: 422
```
```
kind: Status
apiVersion: v1
metadata: {}
status: Failure
message: 'Service "kibana" is invalid: spec.clusterIP: Invalid value: "": field is immutable'
reason: Invalid
details:
  name: kibana
  kind: Service
  causes:
    - reason: FieldValueInvalid
      message: 'Invalid value: "": field is immutable'
      field: spec.clusterIP
code: 422
```
