### ISSUE TITLE
Setting PVC attributes in POM - default volume size

### ISSUE THREAD

**Issue by tdcox** [fabric8io/fabric8#5906]
Setting the default volume size for a PV claim in the POM like so:

```xml
<fabric8.defaultPersistentVolumeClaimRequestsStorage>
    50M
</fabric8.defaultPersistentVolumeClaimRequestsStorage>
```

Results in a JSON entry like:

```json
    "apiVersion" : "v1",
    "kind" : "PersistentVolumeClaim",
    "metadata" : {
      "annotations" : { },
      "labels" : { },
      "name" : "www"
    },
    "spec" : {
      "accessModes" : [ "ReadWriteMany" ],
      "resources" : {
        "limits" : { },
        "requests" : {
          "storage" : "50M"
        }
      },
      "volumeName" : "www"
    }
```
However the deployment fails with:

```
"Unable to mount volumes for pod "nginx-test-vol-75afg_default(d5b09186-fa6d-11e5-91bd-323534663334)": unsupported volume type"
```

There exists a matching PV like so:

```
NAME      CAPACITY   ACCESSMODES   STATUS     CLAIM         REASON    AGE
www       50M        RWX           Released   default/www             14m
```

Full JSON here: https://gist.github.com/tdcox/3fd826045c95513bdb905797026b35d9

**Comment by tdcox** [comment]
Bah, pasting XML doesn't render properly. Above should read:

Setting the default volume size for a PV claim in the POM like so:

fabric8.defaultPersistentVolumeClaimRequestsStorage>50M</fabric8.defaultPersistentVolumeClaimRequestsStorage

**Comment by tdcox** [comment]
OK, I think this is a combination of another bug and a poor error message. Setting defaultPersistentVolumeClaimRequestsStorage does appear to work if the value is less than the capacity of the PV. If the value is larger, the deployment fails with 'unsupported volume type', which is misleading, but could be expected to fail.

What has been throwing me is that once you have deployed a pod against a PV, it will fail to redeploy subsequently, also with the same unhelpful error 'unsupported volume type'. To get it to redeploy, you seem to have to delete the Pod, the PV and the PVC manually, then recreate the PV (it's NFS, so the data is still there). At this point, you can redeploy again. 

So, looks like CI / CD is currently not possible with storage involved unless I'm missing something.

**Comment by rhuss** [comment]
Indeed the error message is really not very helpful but it comes directly from OpenShift. Wonder whether we should open an issue there.

BTW, instead of setting the default claim size, in you example you could have set

```xml
<fabric8.volume.www.requestStorage>50M<fabric8.volume.www.requestStorage>
```

only for your specific volume (which is name `www` in your example)

**Comment by tdcox** [comment]
Thanks. Full POM is here if you wish to reproduce - it's just a Java archetype, tweaked.

https://gist.github.com/tdcox/de9caa18436d833c7b5b11923b29b3f0

**Comment by tdcox** [comment]
I can confirm that the same symptoms occur when using 'requestStorage'.

**Comment by tdcox** [comment]
Looks like this is also flooding the system log with the following every few seconds:

Apr  4 17:33:23 vagrant openshift: E0404 17:33:23.589436     952 persistent_claim.go:74] The volume is not yet bound to the claim. Expected to find the bind on volume.Spec.ClaimRef: &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:www GenerateName: Namespace: SelfLink:/api/v1/persistentvolumes/www UID:14ac6902-fa8a-11e5-91bd-323534663334 ResourceVersion:109875 Generation:0 CreationTimestamp:2016-04-04 17:24:26 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[]} Spec:{Capacity:map[storage:{Amount:1000000000.000 Format:DecimalSI}] PersistentVolumeSource:{GCEPersistentDisk:<nil> AWSElasticBlockStore:<nil> HostPath:<nil> Glusterfs:<nil> NFS:0xc22cc8bec0 RBD:<nil> ISCSI:<nil> FlexVolume:<nil> Cinder:<nil> CephFS:<nil> FC:<nil> Flocker:<nil> AzureFile:<nil>} AccessModes:[ReadWriteMany] ClaimRef:<nil> PersistentVolumeReclaimPolicy:Retain} Status:{Phase:Available Message: Reason:}}
Apr  4 17:33:23 vagrant openshift: E0404 17:33:23.590163     952 kubelet.go:1716] Unable to mount volumes for pod "nginx-test-vol-me5z9_default(3b795bdd-fa8a-11e5-91bd-323534663334)": unsupported volume type; skipping pod
Apr  4 17:33:23 vagrant openshift: E0404 17:33:23.590193     952 pod_workers.go:138] Error syncing pod 3b795bdd-fa8a-11e5-91bd-323534663334, skipping: unsupported volume type

**Comment by rhuss** [comment]
Just trying to reproduce it with this stripped down yaml (see below).

@tdcox what type is your PV ? (hostPath ?) How did you create the PV  ?

```yaml
---
  - 
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    metadata: 
      name: "www"
    spec: 
      accessModes: 
        - "ReadWriteMany"
      resources: 
        requests: 
          storage: "50M"
      volumeName: "www"
  - 
    apiVersion: "v1"
    kind: "ReplicationController"
    metadata: 
      name: "nginx-test-vol"
    spec: 
      replicas: 1
      selector: 
        project: "nginx-test-vol"
        group: "experiments"
      template: 
        metadata: 
          labels: 
            project: "nginx-test-vol"
            group: "experiments"
        spec: 
          containers: 
            - 
              image: "squigl/nginx-test-vol:1.0.1-SNAPSHOT"
              name: "nginx-test-vol"
              volumeMounts: 
                - 
                  mountPath: "/website_files"
                  name: "www"
                  readOnly: false
          volumes: 
            - 
              name: "www"
              persistentVolumeClaim: 
                claimName: "www"
                readOnly: false
```
