### ISSUE TITLE
fluentd daemonset isn't running on kubernetes; invalid field selector for v1beta1.DaemonSet

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5968]
error validating data: found invalid field selector for v1beta1.DaemonSet; if you choose to ignore these errors, turn validation off with --validate=false

yaml used...

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    group: io.fabric8.devops.apps
    project: fluentd
    provider: fabric8
    version: 2.2.164
    package: logging
  name: fluentd
  annotations: {}
spec:
  template:
    metadata:
      labels:
        group: io.fabric8.devops.apps
        project: fluentd
        provider: fabric8
        version: 2.2.164
    spec:
      containers:
        - args: []
          command: []
          env:
            - name: ELASTICSEARCH_HOST
              value: elasticsearch
            - name: ELASTICSEARCH_PORT
              value: '9200'
          image: 'fabric8/fluentd-kubernetes:v1.11'
          name: fluentd
          ports: []
          resources:
            limits:
              cpu: 100m
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
      imagePullSecrets: []
      serviceAccountName: fluentd
      volumes:
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
selector:
  group: io.fabric8.devops.apps
  project: fluentd
  provider: fabric8
  version: 2.2.164
```
