### ISSUE TITLE
Fabric8 maven plugin issues with multiple deployment files

### ISSUE THREAD

**Issue by npvisual** [fabric8io/fabric8#6389]
Hi, I am trying to use fmp with resource fragments such as :

* openidm-service.yml
* postgres-service.yml
* openidm-deployment.yml
* postgres-deployment.yml
* etc...

when I run

`mvn fabric8:resource`

the resulting kubernetes.yml seems fine for the most part, except for the following spec section of each deployment template :

```
- apiVersion: "extensions/v1beta1"
  kind: "Deployment"
[...]
    name: "openidm"
  spec:
    replicas: 1
[...]
    template:
[...]
      spec:
        containers:
        - env:
          - name: "DB_HOST"
            value: "postgres"
          - name: "DB_PASSWORD"
            valueFrom:
              secretKeyRef:
                key: "password.txt"
                name: "postgres-pass"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "forgerock/openidm-zip:latest"
          imagePullPolicy: "IfNotPresent"
          name: "openidm"
          ports:
          - containerPort: 8080
            name: "openidm"
          securityContext:
            privileged: false
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "forgerock/openidm-postgres"
          imagePullPolicy: "IfNotPresent"
          name: "forgerock-openidm-devops"
          securityContext:
            privileged: false
[...]
```

Essentially there is an extraneous `env` declaration, followed by `image`, `imagePullPolicy`, `name` and `securitycontext`.

Those seem to get commingled together in both the `openidm` and `postgres` Deployment sections. But I am not quite sure why or where it's coming from

This creates 2 containers for the deployments, which of course keep on failing.

Removing those extra declarations work as expected : 

```
$ diff target/classes/META-INF/fabric8/kubernetes.yml kubernetes.yml
132,141d131
<         - env:
<           - name: "KUBERNETES_NAMESPACE"
<             valueFrom:
<               fieldRef:
<                 fieldPath: "metadata.namespace"
<           image: "forgerock/openidm-postgres"
<           imagePullPolicy: "IfNotPresent"
<           name: "forgerock-openidm-devops"
<           securityContext:
<             privileged: false
206,215d195
<         - env:
<           - name: "KUBERNETES_NAMESPACE"
<             valueFrom:
<               fieldRef:
<                 fieldPath: "metadata.namespace"
<           image: "forgerock/openidm-postgres"
<           imagePullPolicy: "IfNotPresent"
<           name: "forgerock-openidm-devops"
<           securityContext:
<             privileged: false
```

Any  clues on how to avoid this ?

Thanks,
Nicolas.

**Comment by rawlingsj** [comment]
I've seen this too.  I think I had a mismatch of deployment.metadata.name and pom.xml artifact names.  Not sure if they're supposed to match - @rhuss ?

**Comment by npvisual** [comment]
Hi James,

I think you might be right. I do have 2 images defined in the pom.xml (see below). When I removed the 2nd <image> element, then I don't see the extra declarations in the final `kubernetes.yml` :  
```
        containers:
        - args:
          - "-p"
          - "samples/getting-started"
          env:
          - name: "DB_HOST"
            value: "postgres"
          - name: "DB_PASSWORD"
            valueFrom:
              secretKeyRef:
                key: "password.txt"
                name: "postgres-pass"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "forgerock/openidm-zip:latest"
          imagePullPolicy: "IfNotPresent"
          name: "openidm"
          ports:
          - containerPort: 8080
            name: "openidm"
          securityContext:
            privileged: false
- apiVersion: "extensions/v1beta1"
```
The problem, then, is that it's not building the 2nd image that I need :(.

Here's an extract of the pom.xml
```
              <plugins>
                    <plugin>
                        <groupId>io.fabric8</groupId>
                        <artifactId>fabric8-maven-plugin</artifactId>
                        <version>3.1.52</version>
                        <configuration>
                            <verbose>true</verbose>
                            <resourceDir>src/main/getting-started</resourceDir>
                            <sourceDirectory>src/main/docker</sourceDirectory>
                            <images>
                                <image>
                                    <name>forgerock/openidm-zip</name>
                                    <build>
                                        <dockerFileDir>openidm</dockerFileDir>
                                        <assembly>
                                            <mode>dir</mode>
                                            <inline xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                                    xmlns="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2"
                                                    xsi:schemaLocation="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2 http://maven.apache.org/xsd/assembly-1.1.2.xsd">
                                                <id>openidm</id>
                                                <dependencySets>
                                                    <dependencySet>
                                                        <includes>
                                                            <include>org.forgerock.openidm:openidm-zip</include>
                                                        </includes>
                                                        <outputDirectory>.</outputDirectory>
                                                    </dependencySet>
                                                </dependencySets>
                                            </inline>
                                        </assembly>
                                    </build>
                                </image>
                                <image>
                                    <name>forgerock/openidm-postgres</name>
                                    <build>
                                        <dockerFileDir>postgres</dockerFileDir>
                                        <assembly>
                                            <mode>dir</mode>
                                            <inline xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                                    xmlns="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2"
                                                    xsi:schemaLocation="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2 http://maven.apache.org/xsd/assembly-1.1.2.xsd">
                                                <id>postgres</id>
                                                <dependencySets>
                                                    <dependencySet>
                                                        <includes>
                                                            <include>org.forgerock.openidm:openidm-zip</include>
                                                        </includes>
                                                        <outputDirectory>.</outputDirectory>
                                                    </dependencySet>
                                                </dependencySets>
                                            </inline>
                                        </assembly>
                                    </build>
                                </image>
                            </images>
                        </configuration>
[...]
                    </plugin>
```
