### ISSUE TITLE
Restart fabric8 | error: could not lock config file /app/gogs/data/.gitconfig: Permission denied

### ISSUE THREAD

**Issue by api-maker** [fabric8io/fabric8#6980]
# System configuration
Ubuntu 5.4.0-6ubuntu1~16.04.4
gofabric8, version 0.4.174 (branch: 'master', revision: 'fa273ffa3')
 build date:       '20171108-16:15:48'
 go version:       '1.8.1'
 Minikube:         'v0.23.0'

# Steps to replicate
## Install and start gofabric8 first time everything works fine
* gofabric8 start
* gofabric8 stop
* minikube stop - everything works happy days till this step

## As you had completely stopped gofabric. Now restart

*  gofabric8 start
* kubectl get pods
You will see below Gogs has a problem

## Logs say
Custom path: /opt/gogs/custom
2017/11/09 18:30:01 [T] Log path: /app/gogs/data/logs
2017/11/09 18:30:01 [I] Gogs: Go Git Service
2017/11/09 18:30:01 [.../gogs/models/repo.go:121 NewRepoContext()] [E] Fail to set git user.name(exit status 255): error: could not lock config file /app/gogs/data/.gitconfig: Permission denied

**Comment by argiris-mat** [comment]
I have exactly the same issue. I've tried also installing fabric8 with helm and I see the same behaviour even thought the following configuration exists

`pod.alpha.kubernetes.io/init-containers: >-
          [{"name":"init","image":"busybox","command":["chmod","777","/app/gogs/data"],"resources":{},"volumeMounts":[{"name":"gogs-data","mountPath":"/app/gogs/data"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent"}]
    spec:
      volumes:
        - name: gogs-data
          persistentVolumeClaim:
            claimName: gogs-data`

**Comment by keith-hinde** [comment]
Ditto, same issue here.

**Comment by AmreeshTyagi** [comment]
I am also facing same issue. 
Any fix?

**Comment by fcmfcm01** [comment]
if you are using kubernetes for deploy , try to add security context for "gogs" deployment , here are some code slice 
```
  template:
    metadata:
      annotations:
        configmap.fabric8.io/update-on-change: gogs
        fabric8.io/git-branch: release-v2.2.311
        fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=gogs&var-version=2.2.311
      creationTimestamp: null
      labels:
        group: io.fabric8.devops.apps
        project: gogs
        provider: fabric8
        version: 2.2.311
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - env:
        - name: GOGS_SERVER__ROOT_URL
```
