### ISSUE TITLE
fabric8 can't read the json .kube/config file

### ISSUE THREAD

**Issue by idelix** [fabric8io/fabric8#7037]
Hello, 

I have .kube/config which is formatted in json, it works fine with kubectl but fabric8 can't read it to obtain details of kubernetes cluster.

Command "mvn fabric8:apply" returns following error:
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:apply (default-cli) on project gs-spring-boot-docker: Failure executing: GET at: https://.hcp.canadaeast.azmk8s.io/. Message: Unauthorized! Token may have expired! Please log-in again. Unauthorized. -> [Help 1]

My config file is in following format:

```
{apiVersion: v1, clusters: [{cluster: {certificate-authority-data: ...
server: 'https://<server name>.hcp.westeurope.azmk8s.io:443'}, name: <server name>},
```

Does it mean that only following format is supported ?

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://<cluster name>.hcp.westeurope.azmk8s.io:443
  name: aksdevwe
....
```

Wonder if there is any way around it as I'm using Azure Container Service (AKS) and this is the format CLI command is producing when merging new cluster context information
